Add boilerplate SN-176
Saritasa/dotnet-forge pull request #1
Opened 2023-08-09 08:44 UTC by vasiliy-chefonov

2023-08-10 09:14 UTC, ko-vasilev requested changes

2023-08-10 10:51 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Demo.NetCore7/Program.cs
> +builder.Services.AddDbContext<AppIdentityDbContext>(options =>
I just want to show that we can process several db contexts.

2023-08-10 12:27 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.AspNetCore/Extensions/AdminExtensions.cs
> +        Infrastructure.DependencyInjection.MediatRModule.Register(services);
I guess it's possible to use AddMediatR multiple times per assembly. The core registrations (IMediator etc.) are all done via TryAdd.
![image](https://github.com/Saritasa/dotnet-forge/assets/81791194/42d84dcf-406a-4602-bf62-bc702259244b)

The same is about automapper.
![image](https://github.com/Saritasa/dotnet-forge/assets/81791194/daa2f0a7-2b57-4dde-b3c4-24943dd91b6d)

2023-08-10 12:31 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.BlazorWebAssembly/Saritasa.NetForge.BlazorWebAssembly.csproj
The project is the client that runs on WebAssembly and is hosted by an ASP.NET Core app.

2023-08-21 12:52 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.AspNetCore/Extensions/AdminExtensions.cs
> +        services.AddServerSideBlazor();
There is `TryAdd` inside that allows us to add only service types that haven't already been registered.

2023-08-23 09:50 UTC, dotnetenjoyer approved these changes

2023-08-23 09:50 UTC, dotnetenjoyer commented on src/Saritasa.NetForge.DomainServices/Saritasa.NetForge.DomainServices.csproj
> +      <ProjectReference Include="..\Saritasa.NetForge.UseCases\Saritasa.NetForge.UseCases.csproj" />
I am not sure, but it seems that DomainServices should not refer to UseCases

2023-08-23 09:50 UTC, dotnetenjoyer commented on src/Saritasa.NetForge.Infrastructure.Abstractions/Interfaces/IAdminOptionsBuilder.cs
> +    AdminOptions Options { get; set; }
It may be worth using the Create method to get an instance of AdminOptions

2023-08-23 09:50 UTC, dotnetenjoyer commented on src/Saritasa.NetForge.Infrastructure.EfCore/EfCoreOptionsBuilder.cs
> +    public EfCoreOptions Options { get; set; } = new();
It may be worth make property private

2023-09-14 10:02 UTC, ko-vasilev approved these changes

2023-09-14 10:02 UTC, ko-vasilev commented on src/Saritasa.NetForge.UseCases/Metadata/DTOs/EntityMetadataDto.cs
> +    public string? Name { get; set; }
In which cases can Name and Plural Name be null?

2023-09-25 06:16 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.DomainServices/AdminOptionsBuilder.cs
> +public class AdminOptionsBuilder : IAdminOptionsBuilder
I use the `IOrmOptionsBuilder` just not to depend on the concrete type of ORM such as EF Core.

2023-09-25 06:32 UTC, merged